
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TriageResult` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TriageResult
 * 
 */
export type TriageResultModel = runtime.Types.Result.DefaultSelection<Prisma.$TriageResultPayload>

export type AggregateTriageResult = {
  _count: TriageResultCountAggregateOutputType | null
  _min: TriageResultMinAggregateOutputType | null
  _max: TriageResultMaxAggregateOutputType | null
}

export type TriageResultMinAggregateOutputType = {
  id: string | null
  messageId: string | null
  category: $Enums.Category | null
  urgency: $Enums.Urgency | null
  safeguarding: boolean | null
  disposition: $Enums.Disposition | null
  reason: string | null
  createdAt: Date | null
}

export type TriageResultMaxAggregateOutputType = {
  id: string | null
  messageId: string | null
  category: $Enums.Category | null
  urgency: $Enums.Urgency | null
  safeguarding: boolean | null
  disposition: $Enums.Disposition | null
  reason: string | null
  createdAt: Date | null
}

export type TriageResultCountAggregateOutputType = {
  id: number
  messageId: number
  category: number
  urgency: number
  safeguarding: number
  disposition: number
  reason: number
  rawOutput: number
  createdAt: number
  _all: number
}


export type TriageResultMinAggregateInputType = {
  id?: true
  messageId?: true
  category?: true
  urgency?: true
  safeguarding?: true
  disposition?: true
  reason?: true
  createdAt?: true
}

export type TriageResultMaxAggregateInputType = {
  id?: true
  messageId?: true
  category?: true
  urgency?: true
  safeguarding?: true
  disposition?: true
  reason?: true
  createdAt?: true
}

export type TriageResultCountAggregateInputType = {
  id?: true
  messageId?: true
  category?: true
  urgency?: true
  safeguarding?: true
  disposition?: true
  reason?: true
  rawOutput?: true
  createdAt?: true
  _all?: true
}

export type TriageResultAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TriageResult to aggregate.
   */
  where?: Prisma.TriageResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TriageResults to fetch.
   */
  orderBy?: Prisma.TriageResultOrderByWithRelationInput | Prisma.TriageResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TriageResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TriageResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TriageResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TriageResults
  **/
  _count?: true | TriageResultCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TriageResultMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TriageResultMaxAggregateInputType
}

export type GetTriageResultAggregateType<T extends TriageResultAggregateArgs> = {
      [P in keyof T & keyof AggregateTriageResult]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTriageResult[P]>
    : Prisma.GetScalarType<T[P], AggregateTriageResult[P]>
}




export type TriageResultGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TriageResultWhereInput
  orderBy?: Prisma.TriageResultOrderByWithAggregationInput | Prisma.TriageResultOrderByWithAggregationInput[]
  by: Prisma.TriageResultScalarFieldEnum[] | Prisma.TriageResultScalarFieldEnum
  having?: Prisma.TriageResultScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TriageResultCountAggregateInputType | true
  _min?: TriageResultMinAggregateInputType
  _max?: TriageResultMaxAggregateInputType
}

export type TriageResultGroupByOutputType = {
  id: string
  messageId: string
  category: $Enums.Category
  urgency: $Enums.Urgency
  safeguarding: boolean
  disposition: $Enums.Disposition
  reason: string | null
  rawOutput: runtime.JsonValue
  createdAt: Date
  _count: TriageResultCountAggregateOutputType | null
  _min: TriageResultMinAggregateOutputType | null
  _max: TriageResultMaxAggregateOutputType | null
}

export type GetTriageResultGroupByPayload<T extends TriageResultGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TriageResultGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TriageResultGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TriageResultGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TriageResultGroupByOutputType[P]>
      }
    >
  >



export type TriageResultWhereInput = {
  AND?: Prisma.TriageResultWhereInput | Prisma.TriageResultWhereInput[]
  OR?: Prisma.TriageResultWhereInput[]
  NOT?: Prisma.TriageResultWhereInput | Prisma.TriageResultWhereInput[]
  id?: Prisma.StringFilter<"TriageResult"> | string
  messageId?: Prisma.StringFilter<"TriageResult"> | string
  category?: Prisma.EnumCategoryFilter<"TriageResult"> | $Enums.Category
  urgency?: Prisma.EnumUrgencyFilter<"TriageResult"> | $Enums.Urgency
  safeguarding?: Prisma.BoolFilter<"TriageResult"> | boolean
  disposition?: Prisma.EnumDispositionFilter<"TriageResult"> | $Enums.Disposition
  reason?: Prisma.StringNullableFilter<"TriageResult"> | string | null
  rawOutput?: Prisma.JsonFilter<"TriageResult">
  createdAt?: Prisma.DateTimeFilter<"TriageResult"> | Date | string
  message?: Prisma.XOR<Prisma.MessageScalarRelationFilter, Prisma.MessageWhereInput>
}

export type TriageResultOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  urgency?: Prisma.SortOrder
  safeguarding?: Prisma.SortOrder
  disposition?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  rawOutput?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  message?: Prisma.MessageOrderByWithRelationInput
}

export type TriageResultWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TriageResultWhereInput | Prisma.TriageResultWhereInput[]
  OR?: Prisma.TriageResultWhereInput[]
  NOT?: Prisma.TriageResultWhereInput | Prisma.TriageResultWhereInput[]
  messageId?: Prisma.StringFilter<"TriageResult"> | string
  category?: Prisma.EnumCategoryFilter<"TriageResult"> | $Enums.Category
  urgency?: Prisma.EnumUrgencyFilter<"TriageResult"> | $Enums.Urgency
  safeguarding?: Prisma.BoolFilter<"TriageResult"> | boolean
  disposition?: Prisma.EnumDispositionFilter<"TriageResult"> | $Enums.Disposition
  reason?: Prisma.StringNullableFilter<"TriageResult"> | string | null
  rawOutput?: Prisma.JsonFilter<"TriageResult">
  createdAt?: Prisma.DateTimeFilter<"TriageResult"> | Date | string
  message?: Prisma.XOR<Prisma.MessageScalarRelationFilter, Prisma.MessageWhereInput>
}, "id">

export type TriageResultOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  urgency?: Prisma.SortOrder
  safeguarding?: Prisma.SortOrder
  disposition?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  rawOutput?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.TriageResultCountOrderByAggregateInput
  _max?: Prisma.TriageResultMaxOrderByAggregateInput
  _min?: Prisma.TriageResultMinOrderByAggregateInput
}

export type TriageResultScalarWhereWithAggregatesInput = {
  AND?: Prisma.TriageResultScalarWhereWithAggregatesInput | Prisma.TriageResultScalarWhereWithAggregatesInput[]
  OR?: Prisma.TriageResultScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TriageResultScalarWhereWithAggregatesInput | Prisma.TriageResultScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TriageResult"> | string
  messageId?: Prisma.StringWithAggregatesFilter<"TriageResult"> | string
  category?: Prisma.EnumCategoryWithAggregatesFilter<"TriageResult"> | $Enums.Category
  urgency?: Prisma.EnumUrgencyWithAggregatesFilter<"TriageResult"> | $Enums.Urgency
  safeguarding?: Prisma.BoolWithAggregatesFilter<"TriageResult"> | boolean
  disposition?: Prisma.EnumDispositionWithAggregatesFilter<"TriageResult"> | $Enums.Disposition
  reason?: Prisma.StringNullableWithAggregatesFilter<"TriageResult"> | string | null
  rawOutput?: Prisma.JsonWithAggregatesFilter<"TriageResult">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TriageResult"> | Date | string
}

export type TriageResultCreateInput = {
  id?: string
  category: $Enums.Category
  urgency: $Enums.Urgency
  safeguarding?: boolean
  disposition: $Enums.Disposition
  reason?: string | null
  rawOutput: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  message: Prisma.MessageCreateNestedOneWithoutTriageResultsInput
}

export type TriageResultUncheckedCreateInput = {
  id?: string
  messageId: string
  category: $Enums.Category
  urgency: $Enums.Urgency
  safeguarding?: boolean
  disposition: $Enums.Disposition
  reason?: string | null
  rawOutput: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TriageResultUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
  urgency?: Prisma.EnumUrgencyFieldUpdateOperationsInput | $Enums.Urgency
  safeguarding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  disposition?: Prisma.EnumDispositionFieldUpdateOperationsInput | $Enums.Disposition
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawOutput?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.MessageUpdateOneRequiredWithoutTriageResultsNestedInput
}

export type TriageResultUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
  urgency?: Prisma.EnumUrgencyFieldUpdateOperationsInput | $Enums.Urgency
  safeguarding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  disposition?: Prisma.EnumDispositionFieldUpdateOperationsInput | $Enums.Disposition
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawOutput?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TriageResultCreateManyInput = {
  id?: string
  messageId: string
  category: $Enums.Category
  urgency: $Enums.Urgency
  safeguarding?: boolean
  disposition: $Enums.Disposition
  reason?: string | null
  rawOutput: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TriageResultUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
  urgency?: Prisma.EnumUrgencyFieldUpdateOperationsInput | $Enums.Urgency
  safeguarding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  disposition?: Prisma.EnumDispositionFieldUpdateOperationsInput | $Enums.Disposition
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawOutput?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TriageResultUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  messageId?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
  urgency?: Prisma.EnumUrgencyFieldUpdateOperationsInput | $Enums.Urgency
  safeguarding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  disposition?: Prisma.EnumDispositionFieldUpdateOperationsInput | $Enums.Disposition
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawOutput?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TriageResultListRelationFilter = {
  every?: Prisma.TriageResultWhereInput
  some?: Prisma.TriageResultWhereInput
  none?: Prisma.TriageResultWhereInput
}

export type TriageResultOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TriageResultCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  urgency?: Prisma.SortOrder
  safeguarding?: Prisma.SortOrder
  disposition?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  rawOutput?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TriageResultMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  urgency?: Prisma.SortOrder
  safeguarding?: Prisma.SortOrder
  disposition?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TriageResultMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  messageId?: Prisma.SortOrder
  category?: Prisma.SortOrder
  urgency?: Prisma.SortOrder
  safeguarding?: Prisma.SortOrder
  disposition?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type TriageResultCreateNestedManyWithoutMessageInput = {
  create?: Prisma.XOR<Prisma.TriageResultCreateWithoutMessageInput, Prisma.TriageResultUncheckedCreateWithoutMessageInput> | Prisma.TriageResultCreateWithoutMessageInput[] | Prisma.TriageResultUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.TriageResultCreateOrConnectWithoutMessageInput | Prisma.TriageResultCreateOrConnectWithoutMessageInput[]
  createMany?: Prisma.TriageResultCreateManyMessageInputEnvelope
  connect?: Prisma.TriageResultWhereUniqueInput | Prisma.TriageResultWhereUniqueInput[]
}

export type TriageResultUncheckedCreateNestedManyWithoutMessageInput = {
  create?: Prisma.XOR<Prisma.TriageResultCreateWithoutMessageInput, Prisma.TriageResultUncheckedCreateWithoutMessageInput> | Prisma.TriageResultCreateWithoutMessageInput[] | Prisma.TriageResultUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.TriageResultCreateOrConnectWithoutMessageInput | Prisma.TriageResultCreateOrConnectWithoutMessageInput[]
  createMany?: Prisma.TriageResultCreateManyMessageInputEnvelope
  connect?: Prisma.TriageResultWhereUniqueInput | Prisma.TriageResultWhereUniqueInput[]
}

export type TriageResultUpdateManyWithoutMessageNestedInput = {
  create?: Prisma.XOR<Prisma.TriageResultCreateWithoutMessageInput, Prisma.TriageResultUncheckedCreateWithoutMessageInput> | Prisma.TriageResultCreateWithoutMessageInput[] | Prisma.TriageResultUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.TriageResultCreateOrConnectWithoutMessageInput | Prisma.TriageResultCreateOrConnectWithoutMessageInput[]
  upsert?: Prisma.TriageResultUpsertWithWhereUniqueWithoutMessageInput | Prisma.TriageResultUpsertWithWhereUniqueWithoutMessageInput[]
  createMany?: Prisma.TriageResultCreateManyMessageInputEnvelope
  set?: Prisma.TriageResultWhereUniqueInput | Prisma.TriageResultWhereUniqueInput[]
  disconnect?: Prisma.TriageResultWhereUniqueInput | Prisma.TriageResultWhereUniqueInput[]
  delete?: Prisma.TriageResultWhereUniqueInput | Prisma.TriageResultWhereUniqueInput[]
  connect?: Prisma.TriageResultWhereUniqueInput | Prisma.TriageResultWhereUniqueInput[]
  update?: Prisma.TriageResultUpdateWithWhereUniqueWithoutMessageInput | Prisma.TriageResultUpdateWithWhereUniqueWithoutMessageInput[]
  updateMany?: Prisma.TriageResultUpdateManyWithWhereWithoutMessageInput | Prisma.TriageResultUpdateManyWithWhereWithoutMessageInput[]
  deleteMany?: Prisma.TriageResultScalarWhereInput | Prisma.TriageResultScalarWhereInput[]
}

export type TriageResultUncheckedUpdateManyWithoutMessageNestedInput = {
  create?: Prisma.XOR<Prisma.TriageResultCreateWithoutMessageInput, Prisma.TriageResultUncheckedCreateWithoutMessageInput> | Prisma.TriageResultCreateWithoutMessageInput[] | Prisma.TriageResultUncheckedCreateWithoutMessageInput[]
  connectOrCreate?: Prisma.TriageResultCreateOrConnectWithoutMessageInput | Prisma.TriageResultCreateOrConnectWithoutMessageInput[]
  upsert?: Prisma.TriageResultUpsertWithWhereUniqueWithoutMessageInput | Prisma.TriageResultUpsertWithWhereUniqueWithoutMessageInput[]
  createMany?: Prisma.TriageResultCreateManyMessageInputEnvelope
  set?: Prisma.TriageResultWhereUniqueInput | Prisma.TriageResultWhereUniqueInput[]
  disconnect?: Prisma.TriageResultWhereUniqueInput | Prisma.TriageResultWhereUniqueInput[]
  delete?: Prisma.TriageResultWhereUniqueInput | Prisma.TriageResultWhereUniqueInput[]
  connect?: Prisma.TriageResultWhereUniqueInput | Prisma.TriageResultWhereUniqueInput[]
  update?: Prisma.TriageResultUpdateWithWhereUniqueWithoutMessageInput | Prisma.TriageResultUpdateWithWhereUniqueWithoutMessageInput[]
  updateMany?: Prisma.TriageResultUpdateManyWithWhereWithoutMessageInput | Prisma.TriageResultUpdateManyWithWhereWithoutMessageInput[]
  deleteMany?: Prisma.TriageResultScalarWhereInput | Prisma.TriageResultScalarWhereInput[]
}

export type EnumCategoryFieldUpdateOperationsInput = {
  set?: $Enums.Category
}

export type EnumUrgencyFieldUpdateOperationsInput = {
  set?: $Enums.Urgency
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type EnumDispositionFieldUpdateOperationsInput = {
  set?: $Enums.Disposition
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type TriageResultCreateWithoutMessageInput = {
  id?: string
  category: $Enums.Category
  urgency: $Enums.Urgency
  safeguarding?: boolean
  disposition: $Enums.Disposition
  reason?: string | null
  rawOutput: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TriageResultUncheckedCreateWithoutMessageInput = {
  id?: string
  category: $Enums.Category
  urgency: $Enums.Urgency
  safeguarding?: boolean
  disposition: $Enums.Disposition
  reason?: string | null
  rawOutput: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TriageResultCreateOrConnectWithoutMessageInput = {
  where: Prisma.TriageResultWhereUniqueInput
  create: Prisma.XOR<Prisma.TriageResultCreateWithoutMessageInput, Prisma.TriageResultUncheckedCreateWithoutMessageInput>
}

export type TriageResultCreateManyMessageInputEnvelope = {
  data: Prisma.TriageResultCreateManyMessageInput | Prisma.TriageResultCreateManyMessageInput[]
  skipDuplicates?: boolean
}

export type TriageResultUpsertWithWhereUniqueWithoutMessageInput = {
  where: Prisma.TriageResultWhereUniqueInput
  update: Prisma.XOR<Prisma.TriageResultUpdateWithoutMessageInput, Prisma.TriageResultUncheckedUpdateWithoutMessageInput>
  create: Prisma.XOR<Prisma.TriageResultCreateWithoutMessageInput, Prisma.TriageResultUncheckedCreateWithoutMessageInput>
}

export type TriageResultUpdateWithWhereUniqueWithoutMessageInput = {
  where: Prisma.TriageResultWhereUniqueInput
  data: Prisma.XOR<Prisma.TriageResultUpdateWithoutMessageInput, Prisma.TriageResultUncheckedUpdateWithoutMessageInput>
}

export type TriageResultUpdateManyWithWhereWithoutMessageInput = {
  where: Prisma.TriageResultScalarWhereInput
  data: Prisma.XOR<Prisma.TriageResultUpdateManyMutationInput, Prisma.TriageResultUncheckedUpdateManyWithoutMessageInput>
}

export type TriageResultScalarWhereInput = {
  AND?: Prisma.TriageResultScalarWhereInput | Prisma.TriageResultScalarWhereInput[]
  OR?: Prisma.TriageResultScalarWhereInput[]
  NOT?: Prisma.TriageResultScalarWhereInput | Prisma.TriageResultScalarWhereInput[]
  id?: Prisma.StringFilter<"TriageResult"> | string
  messageId?: Prisma.StringFilter<"TriageResult"> | string
  category?: Prisma.EnumCategoryFilter<"TriageResult"> | $Enums.Category
  urgency?: Prisma.EnumUrgencyFilter<"TriageResult"> | $Enums.Urgency
  safeguarding?: Prisma.BoolFilter<"TriageResult"> | boolean
  disposition?: Prisma.EnumDispositionFilter<"TriageResult"> | $Enums.Disposition
  reason?: Prisma.StringNullableFilter<"TriageResult"> | string | null
  rawOutput?: Prisma.JsonFilter<"TriageResult">
  createdAt?: Prisma.DateTimeFilter<"TriageResult"> | Date | string
}

export type TriageResultCreateManyMessageInput = {
  id?: string
  category: $Enums.Category
  urgency: $Enums.Urgency
  safeguarding?: boolean
  disposition: $Enums.Disposition
  reason?: string | null
  rawOutput: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type TriageResultUpdateWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
  urgency?: Prisma.EnumUrgencyFieldUpdateOperationsInput | $Enums.Urgency
  safeguarding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  disposition?: Prisma.EnumDispositionFieldUpdateOperationsInput | $Enums.Disposition
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawOutput?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TriageResultUncheckedUpdateWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
  urgency?: Prisma.EnumUrgencyFieldUpdateOperationsInput | $Enums.Urgency
  safeguarding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  disposition?: Prisma.EnumDispositionFieldUpdateOperationsInput | $Enums.Disposition
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawOutput?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TriageResultUncheckedUpdateManyWithoutMessageInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.EnumCategoryFieldUpdateOperationsInput | $Enums.Category
  urgency?: Prisma.EnumUrgencyFieldUpdateOperationsInput | $Enums.Urgency
  safeguarding?: Prisma.BoolFieldUpdateOperationsInput | boolean
  disposition?: Prisma.EnumDispositionFieldUpdateOperationsInput | $Enums.Disposition
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rawOutput?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TriageResultSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  messageId?: boolean
  category?: boolean
  urgency?: boolean
  safeguarding?: boolean
  disposition?: boolean
  reason?: boolean
  rawOutput?: boolean
  createdAt?: boolean
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["triageResult"]>

export type TriageResultSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  messageId?: boolean
  category?: boolean
  urgency?: boolean
  safeguarding?: boolean
  disposition?: boolean
  reason?: boolean
  rawOutput?: boolean
  createdAt?: boolean
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["triageResult"]>

export type TriageResultSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  messageId?: boolean
  category?: boolean
  urgency?: boolean
  safeguarding?: boolean
  disposition?: boolean
  reason?: boolean
  rawOutput?: boolean
  createdAt?: boolean
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
}, ExtArgs["result"]["triageResult"]>

export type TriageResultSelectScalar = {
  id?: boolean
  messageId?: boolean
  category?: boolean
  urgency?: boolean
  safeguarding?: boolean
  disposition?: boolean
  reason?: boolean
  rawOutput?: boolean
  createdAt?: boolean
}

export type TriageResultOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "messageId" | "category" | "urgency" | "safeguarding" | "disposition" | "reason" | "rawOutput" | "createdAt", ExtArgs["result"]["triageResult"]>
export type TriageResultInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
}
export type TriageResultIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
}
export type TriageResultIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  message?: boolean | Prisma.MessageDefaultArgs<ExtArgs>
}

export type $TriageResultPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TriageResult"
  objects: {
    message: Prisma.$MessagePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    messageId: string
    category: $Enums.Category
    urgency: $Enums.Urgency
    safeguarding: boolean
    disposition: $Enums.Disposition
    reason: string | null
    rawOutput: runtime.JsonValue
    createdAt: Date
  }, ExtArgs["result"]["triageResult"]>
  composites: {}
}

export type TriageResultGetPayload<S extends boolean | null | undefined | TriageResultDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TriageResultPayload, S>

export type TriageResultCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TriageResultFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TriageResultCountAggregateInputType | true
  }

export interface TriageResultDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TriageResult'], meta: { name: 'TriageResult' } }
  /**
   * Find zero or one TriageResult that matches the filter.
   * @param {TriageResultFindUniqueArgs} args - Arguments to find a TriageResult
   * @example
   * // Get one TriageResult
   * const triageResult = await prisma.triageResult.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TriageResultFindUniqueArgs>(args: Prisma.SelectSubset<T, TriageResultFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TriageResultClient<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TriageResult that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TriageResultFindUniqueOrThrowArgs} args - Arguments to find a TriageResult
   * @example
   * // Get one TriageResult
   * const triageResult = await prisma.triageResult.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TriageResultFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TriageResultFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TriageResultClient<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TriageResult that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TriageResultFindFirstArgs} args - Arguments to find a TriageResult
   * @example
   * // Get one TriageResult
   * const triageResult = await prisma.triageResult.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TriageResultFindFirstArgs>(args?: Prisma.SelectSubset<T, TriageResultFindFirstArgs<ExtArgs>>): Prisma.Prisma__TriageResultClient<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TriageResult that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TriageResultFindFirstOrThrowArgs} args - Arguments to find a TriageResult
   * @example
   * // Get one TriageResult
   * const triageResult = await prisma.triageResult.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TriageResultFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TriageResultFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TriageResultClient<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TriageResults that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TriageResultFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TriageResults
   * const triageResults = await prisma.triageResult.findMany()
   * 
   * // Get first 10 TriageResults
   * const triageResults = await prisma.triageResult.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const triageResultWithIdOnly = await prisma.triageResult.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TriageResultFindManyArgs>(args?: Prisma.SelectSubset<T, TriageResultFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TriageResult.
   * @param {TriageResultCreateArgs} args - Arguments to create a TriageResult.
   * @example
   * // Create one TriageResult
   * const TriageResult = await prisma.triageResult.create({
   *   data: {
   *     // ... data to create a TriageResult
   *   }
   * })
   * 
   */
  create<T extends TriageResultCreateArgs>(args: Prisma.SelectSubset<T, TriageResultCreateArgs<ExtArgs>>): Prisma.Prisma__TriageResultClient<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TriageResults.
   * @param {TriageResultCreateManyArgs} args - Arguments to create many TriageResults.
   * @example
   * // Create many TriageResults
   * const triageResult = await prisma.triageResult.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TriageResultCreateManyArgs>(args?: Prisma.SelectSubset<T, TriageResultCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TriageResults and returns the data saved in the database.
   * @param {TriageResultCreateManyAndReturnArgs} args - Arguments to create many TriageResults.
   * @example
   * // Create many TriageResults
   * const triageResult = await prisma.triageResult.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TriageResults and only return the `id`
   * const triageResultWithIdOnly = await prisma.triageResult.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TriageResultCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TriageResultCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TriageResult.
   * @param {TriageResultDeleteArgs} args - Arguments to delete one TriageResult.
   * @example
   * // Delete one TriageResult
   * const TriageResult = await prisma.triageResult.delete({
   *   where: {
   *     // ... filter to delete one TriageResult
   *   }
   * })
   * 
   */
  delete<T extends TriageResultDeleteArgs>(args: Prisma.SelectSubset<T, TriageResultDeleteArgs<ExtArgs>>): Prisma.Prisma__TriageResultClient<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TriageResult.
   * @param {TriageResultUpdateArgs} args - Arguments to update one TriageResult.
   * @example
   * // Update one TriageResult
   * const triageResult = await prisma.triageResult.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TriageResultUpdateArgs>(args: Prisma.SelectSubset<T, TriageResultUpdateArgs<ExtArgs>>): Prisma.Prisma__TriageResultClient<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TriageResults.
   * @param {TriageResultDeleteManyArgs} args - Arguments to filter TriageResults to delete.
   * @example
   * // Delete a few TriageResults
   * const { count } = await prisma.triageResult.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TriageResultDeleteManyArgs>(args?: Prisma.SelectSubset<T, TriageResultDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TriageResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TriageResultUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TriageResults
   * const triageResult = await prisma.triageResult.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TriageResultUpdateManyArgs>(args: Prisma.SelectSubset<T, TriageResultUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TriageResults and returns the data updated in the database.
   * @param {TriageResultUpdateManyAndReturnArgs} args - Arguments to update many TriageResults.
   * @example
   * // Update many TriageResults
   * const triageResult = await prisma.triageResult.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TriageResults and only return the `id`
   * const triageResultWithIdOnly = await prisma.triageResult.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TriageResultUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TriageResultUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TriageResult.
   * @param {TriageResultUpsertArgs} args - Arguments to update or create a TriageResult.
   * @example
   * // Update or create a TriageResult
   * const triageResult = await prisma.triageResult.upsert({
   *   create: {
   *     // ... data to create a TriageResult
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TriageResult we want to update
   *   }
   * })
   */
  upsert<T extends TriageResultUpsertArgs>(args: Prisma.SelectSubset<T, TriageResultUpsertArgs<ExtArgs>>): Prisma.Prisma__TriageResultClient<runtime.Types.Result.GetResult<Prisma.$TriageResultPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TriageResults.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TriageResultCountArgs} args - Arguments to filter TriageResults to count.
   * @example
   * // Count the number of TriageResults
   * const count = await prisma.triageResult.count({
   *   where: {
   *     // ... the filter for the TriageResults we want to count
   *   }
   * })
  **/
  count<T extends TriageResultCountArgs>(
    args?: Prisma.Subset<T, TriageResultCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TriageResultCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TriageResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TriageResultAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TriageResultAggregateArgs>(args: Prisma.Subset<T, TriageResultAggregateArgs>): Prisma.PrismaPromise<GetTriageResultAggregateType<T>>

  /**
   * Group by TriageResult.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TriageResultGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TriageResultGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TriageResultGroupByArgs['orderBy'] }
      : { orderBy?: TriageResultGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TriageResultGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTriageResultGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TriageResult model
 */
readonly fields: TriageResultFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TriageResult.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TriageResultClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  message<T extends Prisma.MessageDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MessageDefaultArgs<ExtArgs>>): Prisma.Prisma__MessageClient<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TriageResult model
 */
export interface TriageResultFieldRefs {
  readonly id: Prisma.FieldRef<"TriageResult", 'String'>
  readonly messageId: Prisma.FieldRef<"TriageResult", 'String'>
  readonly category: Prisma.FieldRef<"TriageResult", 'Category'>
  readonly urgency: Prisma.FieldRef<"TriageResult", 'Urgency'>
  readonly safeguarding: Prisma.FieldRef<"TriageResult", 'Boolean'>
  readonly disposition: Prisma.FieldRef<"TriageResult", 'Disposition'>
  readonly reason: Prisma.FieldRef<"TriageResult", 'String'>
  readonly rawOutput: Prisma.FieldRef<"TriageResult", 'Json'>
  readonly createdAt: Prisma.FieldRef<"TriageResult", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TriageResult findUnique
 */
export type TriageResultFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultInclude<ExtArgs> | null
  /**
   * Filter, which TriageResult to fetch.
   */
  where: Prisma.TriageResultWhereUniqueInput
}

/**
 * TriageResult findUniqueOrThrow
 */
export type TriageResultFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultInclude<ExtArgs> | null
  /**
   * Filter, which TriageResult to fetch.
   */
  where: Prisma.TriageResultWhereUniqueInput
}

/**
 * TriageResult findFirst
 */
export type TriageResultFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultInclude<ExtArgs> | null
  /**
   * Filter, which TriageResult to fetch.
   */
  where?: Prisma.TriageResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TriageResults to fetch.
   */
  orderBy?: Prisma.TriageResultOrderByWithRelationInput | Prisma.TriageResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TriageResults.
   */
  cursor?: Prisma.TriageResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TriageResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TriageResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TriageResults.
   */
  distinct?: Prisma.TriageResultScalarFieldEnum | Prisma.TriageResultScalarFieldEnum[]
}

/**
 * TriageResult findFirstOrThrow
 */
export type TriageResultFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultInclude<ExtArgs> | null
  /**
   * Filter, which TriageResult to fetch.
   */
  where?: Prisma.TriageResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TriageResults to fetch.
   */
  orderBy?: Prisma.TriageResultOrderByWithRelationInput | Prisma.TriageResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TriageResults.
   */
  cursor?: Prisma.TriageResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TriageResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TriageResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TriageResults.
   */
  distinct?: Prisma.TriageResultScalarFieldEnum | Prisma.TriageResultScalarFieldEnum[]
}

/**
 * TriageResult findMany
 */
export type TriageResultFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultInclude<ExtArgs> | null
  /**
   * Filter, which TriageResults to fetch.
   */
  where?: Prisma.TriageResultWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TriageResults to fetch.
   */
  orderBy?: Prisma.TriageResultOrderByWithRelationInput | Prisma.TriageResultOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TriageResults.
   */
  cursor?: Prisma.TriageResultWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TriageResults from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TriageResults.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TriageResults.
   */
  distinct?: Prisma.TriageResultScalarFieldEnum | Prisma.TriageResultScalarFieldEnum[]
}

/**
 * TriageResult create
 */
export type TriageResultCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultInclude<ExtArgs> | null
  /**
   * The data needed to create a TriageResult.
   */
  data: Prisma.XOR<Prisma.TriageResultCreateInput, Prisma.TriageResultUncheckedCreateInput>
}

/**
 * TriageResult createMany
 */
export type TriageResultCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TriageResults.
   */
  data: Prisma.TriageResultCreateManyInput | Prisma.TriageResultCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TriageResult createManyAndReturn
 */
export type TriageResultCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * The data used to create many TriageResults.
   */
  data: Prisma.TriageResultCreateManyInput | Prisma.TriageResultCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TriageResult update
 */
export type TriageResultUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultInclude<ExtArgs> | null
  /**
   * The data needed to update a TriageResult.
   */
  data: Prisma.XOR<Prisma.TriageResultUpdateInput, Prisma.TriageResultUncheckedUpdateInput>
  /**
   * Choose, which TriageResult to update.
   */
  where: Prisma.TriageResultWhereUniqueInput
}

/**
 * TriageResult updateMany
 */
export type TriageResultUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TriageResults.
   */
  data: Prisma.XOR<Prisma.TriageResultUpdateManyMutationInput, Prisma.TriageResultUncheckedUpdateManyInput>
  /**
   * Filter which TriageResults to update
   */
  where?: Prisma.TriageResultWhereInput
  /**
   * Limit how many TriageResults to update.
   */
  limit?: number
}

/**
 * TriageResult updateManyAndReturn
 */
export type TriageResultUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * The data used to update TriageResults.
   */
  data: Prisma.XOR<Prisma.TriageResultUpdateManyMutationInput, Prisma.TriageResultUncheckedUpdateManyInput>
  /**
   * Filter which TriageResults to update
   */
  where?: Prisma.TriageResultWhereInput
  /**
   * Limit how many TriageResults to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TriageResult upsert
 */
export type TriageResultUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultInclude<ExtArgs> | null
  /**
   * The filter to search for the TriageResult to update in case it exists.
   */
  where: Prisma.TriageResultWhereUniqueInput
  /**
   * In case the TriageResult found by the `where` argument doesn't exist, create a new TriageResult with this data.
   */
  create: Prisma.XOR<Prisma.TriageResultCreateInput, Prisma.TriageResultUncheckedCreateInput>
  /**
   * In case the TriageResult was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TriageResultUpdateInput, Prisma.TriageResultUncheckedUpdateInput>
}

/**
 * TriageResult delete
 */
export type TriageResultDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultInclude<ExtArgs> | null
  /**
   * Filter which TriageResult to delete.
   */
  where: Prisma.TriageResultWhereUniqueInput
}

/**
 * TriageResult deleteMany
 */
export type TriageResultDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TriageResults to delete
   */
  where?: Prisma.TriageResultWhereInput
  /**
   * Limit how many TriageResults to delete.
   */
  limit?: number
}

/**
 * TriageResult without action
 */
export type TriageResultDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TriageResult
   */
  select?: Prisma.TriageResultSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TriageResult
   */
  omit?: Prisma.TriageResultOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TriageResultInclude<ExtArgs> | null
}
