
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Category = {
  ACADEMIC: 'ACADEMIC',
  FINANCIAL: 'FINANCIAL',
  VISA_IMMIGRATION: 'VISA_IMMIGRATION',
  HOUSING: 'HOUSING',
  HEALTH_WELLBEING: 'HEALTH_WELLBEING',
  OTHER: 'OTHER'
} as const

export type Category = (typeof Category)[keyof typeof Category]


export const Urgency = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
} as const

export type Urgency = (typeof Urgency)[keyof typeof Urgency]


export const Disposition = {
  HANDLE_NOW: 'HANDLE_NOW',
  ASK_CLARIFYING: 'ASK_CLARIFYING',
  ESCALATE: 'ESCALATE'
} as const

export type Disposition = (typeof Disposition)[keyof typeof Disposition]


export const ConversationStatus = {
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED'
} as const

export type ConversationStatus = (typeof ConversationStatus)[keyof typeof ConversationStatus]


export const MessageRole = {
  STUDENT: 'STUDENT',
  ASSISTANT: 'ASSISTANT',
  SYSTEM: 'SYSTEM'
} as const

export type MessageRole = (typeof MessageRole)[keyof typeof MessageRole]


export const CaseStatus = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED'
} as const

export type CaseStatus = (typeof CaseStatus)[keyof typeof CaseStatus]
